services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      VIRTUAL_HOST: "ci.lucko.me,download.luckperms.net"
      VIRTUAL_PORT: "8080"
      JENKINS_JAVA_OPTS: "-Xmx500m"
    volumes:
      - data:/var/jenkins_home
    networks:
      - "default"
      - "jenkins"

  jenkins-agent01:
    image: jenkins/ssh-agent:jdk21
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBLIC_KEY}
    volumes:
      - maven-cache:/home/jenkins/.m2
      - gradle-cache:/home/jenkins/.gradle
    networks:
      - "jenkins"
    cpus: 2

  backup:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 0 2 * * 2" # tuesday at 2am
      RESTIC_REPOSITORY: ${RESTIC_REPO}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/jenkinsdata
      RESTIC_BACKUP_ARGS: >-
        --tag docker-jenkins
        --exclude /mnt/jenkinsdata/tools
        --exclude /mnt/jenkinsdata/workspace
        --exclude /mnt/jenkinsdata/logs
        --exclude /mnt/jenkinsdata/monitoring
        --exclude /mnt/jenkinsdata/.m2
        --exclude /mnt/jenkinsdata/.gradle
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 4
        --keep-weekly 4
        --keep-monthly 4
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      # send metrics about backup status/size/filecount to prometheus
      POST_COMMANDS_SUCCESS: |-
        restic stats --json > stats.json
        apk add --no-cache jq
        echo "restic_status 1" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_jenkins
        echo "restic_total_size $$(cat stats.json | jq '.total_size')" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_jenkins
        echo "restic_total_file_count $$(cat stats.json | jq '.total_file_count')" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_jenkins
      POST_COMMANDS_FAILURE: |-
        echo "restic_status 0" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_jenkins
    volumes:
      - data:/mnt/jenkinsdata:ro

  backup-prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "false"
      PRUNE_CRON: "0 0 3 * * 2" # tuesday at 3am
      RESTIC_REPOSITORY: ${RESTIC_REPO}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}

volumes:
  data:
  maven-cache:
  gradle-cache:

networks:
  default:
    name: "services"
    external: true
  jenkins:
    name: "jenkins"
    external: true
