---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Install useful packages
  ansible.builtin.apt:
    update_cache: yes
    pkg: "{{ basic_setup_packages }}"
