services:
  nexus:
    image: sonatype/nexus3
    platform: linux/amd64
    environment:
      VIRTUAL_HOST: "nexus.lucko.me,repo.lucko.me,libraries.luckperms.net"
      VIRTUAL_PORT: "8081"
      INSTALL4J_ADD_VM_PARAMS: "-Xms200m -Xmx500m -XX:MaxDirectMemorySize=500m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - data:/nexus-data

  backup:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 0 2 * * 1" # monday at 2am
      RESTIC_REPOSITORY: ${RESTIC_REPO}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/nexusdata/blobs /mnt/nexusdata/keystores /mnt/nexusdata/dbbackups
      RESTIC_BACKUP_ARGS: >-
        --tag docker-nexus
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 4
        --keep-weekly 4
        --keep-monthly 4
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
      # send metrics about backup status/size/filecount to prometheus
      POST_COMMANDS_SUCCESS: |-
        restic stats --json > stats.json
        apk add --no-cache jq
        echo "restic_status 1" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_nexus
        echo "restic_total_size $$(cat stats.json | jq '.total_size')" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_nexus
        echo "restic_total_file_count $$(cat stats.json | jq '.total_file_count')" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_nexus
      POST_COMMANDS_FAILURE: |-
        echo "restic_status 0" | curl --data-binary @- http://pushgateway:9091/metrics/job/backup_nexus
    volumes:
      - data:/mnt/nexusdata:ro

  backup-prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "false"
      PRUNE_CRON: "0 0 3 * * 1" # monday at 3am
      RESTIC_REPOSITORY: ${RESTIC_REPO}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}

volumes:
  data:

networks:
  default:
    name: "services"
    external: true
